app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

spring:
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:36760/railway?sslmode=require
    username: postgres
    password: gASEdAWmqCjaGAfapIeZqCkObUXuhNeL
    driver-class-name: org.postgresql.Driver


  jpa:
    transaction-manager: transactionManager
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    clean-disabled: true

  mail:
    host: in-v3.mailjet.com
    port: 587
    username: 37d203cfe4a184fef576db74d6774438
    password: 9c114704da4644404d4da3f387a6a6a2
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  profiles:
    active: default

  jwt:
    secret: "aJH3xcaotUUB+7R2FDyDMxWnejGZrNFGtfa7wQ8bqhw="


paypal:
  client-id: AcBlu4JP-XYaKyE0zwqqfbSHr6gAC396CX58suzZamypO1J5ISPK3TddvRi5xZLf5RO7rEuAc_QO2uKI
  client-secret: EGGcHtKd6yyMAdsdHG5pO8Gb2sxaHZohou7OD4DJ0KB-73WXnJh3wo73nkB13QkYD-6vhCEyT1hpmex1
  mode: sandbox



logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        web: DEBUG

server:
  port: ${PORT:8080}